language: node_js
os:
  - linux
node_js:
  - 14
script:
  - yarn build
  - yarn start
branches:
  except:
    - master
deploy:
  provider: npm
  email: "nicolas@cochard.co.uk"
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true